# This file was generated by GoReleaser. DO NOT EDIT.
class Cheat < Formula
  desc "A fast and flexible cheatsheet manager built with Go"
  homepage "https://github.com/darrikonn/cheat"
  url "https://github.com/darrikonn/cheat/releases/download/v1.1.0/cheat-v1.1.0-macOS-64bit.tar.gz"
  version "1.1.0"
  sha256 "156b9463b72b6e566f3f8b142837a8ee19af612819cd6ec79abe9cbe409c380a"

  def install
    bin.install "cheat"
  end

  test do
    system "#{bin}/cheat -v"
  end
end
